### ISSUE TITLE
Use a switch different from the z endstop one

### ISSUE THREAD

**Issue by TheRoboCoder** [hawkeyexp/auto_offset_z#1]
I have 2 optical sensors, one for each side of the z axis homing of my printer (bed slinger) to ensure x axis is straight, could it be possible to perform the same routine with an additional mechanical switch (attached on bed) different from the optical z endstop switches? Also could it be possible to turn all the routine and code into a single klipper macro block ?

**Comment by bmkahl** [comment]
Using a conductive probe would greatly benefit from a new Z_offset endstop. Setting this up to use a conductive Z endstop works real well but requires to clean the nozzle each time before it homes. 

If we can set it up to go to the X/Y position and then move until the pin is triggered we could leave the Z homing endstop alone.
